/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v2_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_v2_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/sessions/{session_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply */
        post: operations["apply_api_v2_sessions__session_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/sessions/{session_id}/change-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Plan */
        post: operations["change_plan_api_v2_sessions__session_id__change_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/sessions/{session_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Files */
        post: operations["upload_files_api_v2_sessions__session_id__files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/sessions/{session_id}/outputs.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Outputs Zip */
        get: operations["download_outputs_zip_api_v2_sessions__session_id__outputs_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/sessions/{session_id}/outputs/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Output */
        get: operations["download_output_api_v2_sessions__session_id__outputs__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/sessions/{session_id}/preview-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Preview Job */
        post: operations["create_preview_job_api_v2_sessions__session_id__preview_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/sessions/{session_id}/preview-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preview Job */
        get: operations["get_preview_job_api_v2_sessions__session_id__preview_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/sessions/{session_id}/preview-jobs/{job_id}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Step Preview Job */
        post: operations["step_preview_job_api_v2_sessions__session_id__preview_jobs__job_id__steps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplyFileResult */
        ApplyFileResult: {
            /** Backup */
            backup?: string | null;
            error?: components["schemas"]["ErrorResponse"] | null;
            /** Output Sha256 */
            output_sha256?: string | null;
            /** Pair Id */
            pair_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "unchanged" | "failed";
            /** Ttml */
            ttml: string;
        };
        /** ApplyRequest */
        ApplyRequest: {
            /** Selections */
            selections?: components["schemas"]["Selection"][];
            /** Snapshot Id */
            snapshot_id: string;
        };
        /** ApplyResponse */
        ApplyResponse: {
            /** Failed */
            failed: number;
            /** Files */
            files?: components["schemas"]["ApplyFileResult"][];
            /** Skipped */
            skipped: number;
            /** Snapshot Id */
            snapshot_id: string;
            /** Succeeded */
            succeeded: number;
        };
        /** Body_upload_files_api_v2_sessions__session_id__files_post */
        Body_upload_files_api_v2_sessions__session_id__files_post: {
            /** Files */
            files: string[];
        };
        /** Candidate */
        Candidate: {
            /** Album */
            album?: string | null;
            /** Aliases */
            aliases?: string[];
            /** Artists */
            artists?: string[];
            /** Duration Ms */
            duration_ms?: number | null;
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
            /** Group */
            group?: string | null;
            /** Id */
            id: string;
            /** Identifiers */
            identifiers?: {
                [key: string]: string;
            };
            /**
             * Rank
             * @default 1
             */
            rank: number;
            /**
             * Recommended
             * @default false
             */
            recommended: boolean;
            /** Release Date */
            release_date?: string | null;
            /** Source */
            source: string;
            /** Title */
            title?: string | null;
        };
        /** ChangePlanRequest */
        ChangePlanRequest: {
            selection: components["schemas"]["Selection"];
            /** Snapshot Id */
            snapshot_id: string;
        };
        /** ChangePlanResponse */
        ChangePlanResponse: {
            /** Changed */
            changed: boolean;
            /** Final Text */
            final_text: string;
            /** Input Sha256 */
            input_sha256: string;
            metadata: components["schemas"]["MetadataChangeSummary"];
            normalization: components["schemas"]["NormalizationSummary"];
            /** Output Sha256 */
            output_sha256: string;
            /** Pair Id */
            pair_id: string;
            /** Snapshot Id */
            snapshot_id: string;
        };
        /** ChangePlanSummary */
        ChangePlanSummary: {
            /** Changed */
            changed: boolean;
            /** Final Text */
            final_text: string;
            /** Input Sha256 */
            input_sha256: string;
            metadata: components["schemas"]["MetadataChangeSummary"];
            normalization: components["schemas"]["NormalizationSummary"];
            /** Output Sha256 */
            output_sha256: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
        };
        /** Evidence */
        Evidence: {
            /** Actual */
            actual?: string | null;
            /** Expected */
            expected?: string | null;
            /** Field */
            field: string;
            /** Relation */
            relation: string;
        };
        /** MetadataChangeSummary */
        MetadataChangeSummary: {
            /** Added */
            added?: {
                [key: string]: string[];
            };
            /**
             * Changed
             * @default false
             */
            changed: boolean;
            /** Replaced */
            replaced?: {
                [key: string]: string[];
            };
            /** Skipped */
            skipped?: {
                [key: string]: string[];
            };
        };
        /** NormalizationSummary */
        NormalizationSummary: {
            /**
             * Body Text Changed
             * @default false
             */
            body_text_changed: boolean;
            /**
             * Changed
             * @default false
             */
            changed: boolean;
            /**
             * Language Changed
             * @default false
             */
            language_changed: boolean;
            /**
             * Removed Translations
             * @default 0
             */
            removed_translations: number;
            /**
             * Removed Transliterations
             * @default 0
             */
            removed_transliterations: number;
        };
        /** PairFile */
        PairFile: {
            /** Filename */
            filename: string;
            /** Sha256 */
            sha256: string;
        };
        /** PairFiles */
        PairFiles: {
            audio?: components["schemas"]["PairFile"] | null;
            ttml: components["schemas"]["PairFile"];
        };
        /** PairPreview */
        PairPreview: {
            baseline_change_plan: components["schemas"]["ChangePlanSummary"];
            default_selection: components["schemas"]["Selection"];
            files: components["schemas"]["PairFiles"];
            /** Pair Id */
            pair_id: string;
            /** Sources */
            sources?: {
                [key: string]: components["schemas"]["SourceResult"];
            };
        };
        /** PairingIssue */
        PairingIssue: {
            /** Audio Candidates */
            audio_candidates?: string[];
            /** Code */
            code: string;
            /** Pair Id */
            pair_id: string;
            /** Ttml Path */
            ttml_path: string;
        };
        /** PairingPair */
        PairingPair: {
            /** Audio Candidates */
            audio_candidates?: string[];
            /** Audio Path */
            audio_path?: string | null;
            /** Pair Id */
            pair_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "paired" | "ttml_only" | "ambiguous";
            /** Ttml Path */
            ttml_path: string;
        };
        /** PairingPlanResponse */
        PairingPlanResponse: {
            /** Issues */
            issues?: components["schemas"]["PairingIssue"][];
            /** Pairs */
            pairs?: components["schemas"]["PairingPair"][];
        };
        /** PreviewJob */
        PreviewJob: {
            /** Completed */
            completed: number;
            /** Errors */
            errors?: components["schemas"]["ErrorResponse"][];
            /** Job Id */
            job_id: string;
            /** Results */
            results?: components["schemas"]["PairPreview"][];
            /** Snapshot Id */
            snapshot_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "completed_with_errors" | "failed";
            /** Total */
            total: number;
        };
        /** Selection */
        Selection: {
            /** Pair Id */
            pair_id: string;
            /** Sources */
            sources?: {
                [key: string]: string[];
            };
        };
        /** SessionResponse */
        SessionResponse: {
            /** Session Id */
            session_id: string;
        };
        /** SourceResult */
        SourceResult: {
            /** Candidates */
            candidates?: components["schemas"]["Candidate"][];
            /** Groups */
            groups?: {
                [key: string]: string[];
            };
            /** Recommended Ids */
            recommended_ids?: string[];
            /** Source */
            source: string;
            /** Warnings */
            warnings?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_session_api_v2_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_session_api_v2_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    apply_api_v2_sessions__session_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    change_plan_api_v2_sessions__session_id__change_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePlanResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_files_api_v2_sessions__session_id__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_files_api_v2_sessions__session_id__files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingPlanResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    download_outputs_zip_api_v2_sessions__session_id__outputs_zip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    download_output_api_v2_sessions__session_id__outputs__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_preview_job_api_v2_sessions__session_id__preview_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewJob"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_preview_job_api_v2_sessions__session_id__preview_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewJob"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    step_preview_job_api_v2_sessions__session_id__preview_jobs__job_id__steps_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewJob"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
